### ISSUE TITLE
Deprecate in favor of gulp-htmltidy

### ISSUE THREAD

**Issue by kflorence** [colynb/gulp-html-prettify#2]
https://github.com/ayhankuru/gulp-htmltidy

The above has better formatting options http://w3c.github.io/tidy-html5/quickref.html

**Comment by colynb** [comment]
Are you kidding? Why would I do that?

**Comment by kflorence** [comment]
No, I'm not kidding. The less plugins out there that do the same thing, the better. And that other plugin happens to wrap a better node module.

**Comment by colynb** [comment]
That's what the rating system is for. Also, my plugin has been around longer than the other one and I happen to know there are large teams dependent on it right now.

**Comment by kflorence** [comment]
Yeah, that's why I suggested deprecation, not removing it.

On Sunday, December 7, 2014, Colyn Brown notifications@github.com wrote:

> That what the rating system is for. Also, my plugin has been around longer
> than the other one and I happen to know there are large teams dependent on
> it right now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/colynb/gulp-html-prettify/issues/2#issuecomment-65966503
> .

## 

Kyle Florence
http://kflorence.com
